# src/main/resources/application-oauth2.yml

spring:
  security:
    oauth2:
      client:
        registration:
          # --- Google 로그인 설정 ---
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri:  ${GOOGLE_REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          # --- Kakao 로그인 설정 ---
          kakao:
            client-id: ${KAKAO_CLIENT}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

          # --- Naver 로그인 설정 (추가) ---
          naver:
            client-id: ${NAVER_CLIENT}
            client-secret: ${NAVER_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email
              - birthday

        # --- Provider별 세부 설정 (Kakao, Naver는 직접 지정 필요) ---
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 사용자 정보를 식별할 고유 키 값

          # --- Naver Provider 설정 (추가) ---
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버는 사용자 정보를 response 객체 안에 담아서 줌

